### ISSUE TITLE
LeanTween-2.50.4.unitypackage.zip Corrupt

### ISSUE THREAD

**Issue by BrianOSH** [JohannesDeml/LeanTween#5]
LeanTween-2.50.4.unitypackage.zip
seems to be a corrupt file.

**Comment by JohannesDeml** [comment]
Hi @BrianOSH,

thanks for the note. It seems like there was a problem with GZIP in this case. I zipped the package again and replaced it in the release. Can you check again if it is working for you now?

**Comment by BrianOSH** [comment]
Hi
  Thanks for the quick response. I’ve downloaded it and it unzipped successfully.
Thanks again.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JohannesDeml** [comment]
Awesome, thanks for verifying and posting the issue in the first place!
